### PR TITLE
[CSS] Fix toolbar vertical alignment

### PR DESCRIPTION
**Pull request by gamerinshaft**
[before]
スクリーンショット 2019-06-02 3 34 18

<hr>

[after]
スクリーンショット 2019-06-02 3 35 38

### CODE REVIEW

**Comment by tommoor** [comment]
Hey, this isn't an issue on master for me – which browser are you testing in? It looks like this is a screenshot from the included example page – is that correct?

**Comment by gamerinshaft** [comment]
I use electron `4.0.6` from [electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate)
I attached screenshot about the page.

スクリーンショット 2019-06-13 10 54 02

**Comment by tommoor** [comment]
Hmmm, fair. This is just very strange that changing the vertical align of the separator would make any difference to this 😆

**Comment by tommoor** [comment]
I predict this is fixed by fd46b92 – unfortunately this PR isn't mergeable as it does affect the layout of the toolbar in "normal" scenarios.

**Pull request closed without merging**
