### PR TITLE
Upgrade Slate

### PR DESCRIPTION
**Pull request by tommoor**
There's a different breaking version every couple of weeks it seems, becoming increasingly difficult to stay on top of and various plugins are falling behind 😢 

### Plugins

- [ ] `slate-edit-code` supports [version 0.33](https://github.com/GitbookIO/slate-edit-code/blob/master/package.json#L16)
  - [PR for Slate 0.37](https://github.com/GitbookIO/slate-edit-code/pull/46)
- [ ] `slate-edit-list` supports [version 0.32](https://github.com/GitbookIO/slate-edit-list/blob/master/package.json#L10)
  - [PR for Slate 0.40](https://github.com/GitbookIO/slate-edit-list/pull/83)
- [ ] `slate-prism` supports [version 0.32](https://github.com/GitbookIO/slate-prism/blob/master/package.json#L15)
  - [PR for Slate 0.37](https://github.com/GitbookIO/slate-prism/pull/13)
- [ ] `slate-trailing-block` supports [version 0.32](https://github.com/GitbookIO/slate-trailing-block/blob/master/package.json#L10)
- [x] `slate-paste-linkify` supports [version 0.37](https://github.com/ianstormtaylor/slate-plugins/blob/master/packages/slate-paste-linkify/package.json)

### CODE REVIEW

**Comment by linonetwo** [comment]
No breaking changes between 0.37 and 0.40, so all of them can target 0.40

**Comment by dselman** [comment]
Latest Slate is now up to 0.44.9. Are there any plans to update `rich-markdown-editor`?

**Comment by linonetwo** [comment]
There seems to be a huge API change in slatejs, from immutable to plain object. Maybe should wait for that.

**Comment by tommoor** [comment]
closing in favor of https://github.com/outline/rich-markdown-editor/pull/59 – attempting to upgrade to 44.0

**Pull request closed without merging**
