### PR TITLE
Hidden toolbar buttons

### PR DESCRIPTION
**Pull request by jfrolich**
This PR will allow users to selectively turn off toolbar buttons in the theme.

I also created a type definition for the theme.

### CODE REVIEW

**Comment by tommoor** [comment]
Would you mind removing the extensive `yarn.lock` update from this PR before I merge?

**Comment by jorilallo** [comment]
@tommoor passing arrays of formatting options would be cool. I was thinking of adding this as I want to edit mine and remove the block toolbar

**Comment by jfrolich** [comment]
Yeah open to API/naming feedback. I needed to remove H1 in my app. Happy to do some polish.

I will remove the yarn.lock 👍

**Comment by jfrolich** [comment]
brought back yarn.lock from master (so no diff). BTW it would be great to fix the issue with node 10 in yarn.lock!

**Comment by tommoor** [comment]
Thanks!

@jorilallo it seems reasonable to merge this as a non breaking change and then if someone wants to build out passing arrays of formatting options that can succeed this API at that time.

**Comment by jorilallo** [comment]
Yeah I might look into it once it's more timely for myself. But good to know you're open to it :)

**Pull request merged**
